title: Meta Space
author: Meta Network
logo_img: https://ipfs.fleek.co/ipfs/bafybeidyi56ytz2gkossffp43ls4flx7u3ijd75kovdi5kyohoazhwebv4
author_img: https://ipfs.fleek.co/ipfs/bafybeiccss3figrixd5qhhv6i6zhbz5chmyls6ja5kscu6drg7fnjcnxgm
links:
  Hexo:
    url: https://hexo.io
  MetaNetwork:
    url: https://meta-network.mttk.net
about:
  description: designed by theme-kaze
  social_links:
    - { icon: "icon-github", link: "https://github.com/Meta-Network" }
